services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wcprediction
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
