spring.application.name=wc-prediction
spring.profiles.active=dev
server.port=8080

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Expose the health endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

logging.level.org.springframework.web=DEBUG

# App version - bump on each deployment to force UI logout
app.version=1.2.0
